import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import { api, post } from "../../lib/api";
import { useFacilityScope } from "../../lib/facilityScope";
import { useI18n } from "../../i18n";
import {
  Badge,
  Button,
  Card,
  EmptyState,
  Field,
  Input,
  ListFilters,
  LoadingScreen,
  Modal,
  Money,
  PageHeader,
  Pagination,
  SearchableSelect,
  StatusBadge,
  Table,
  Td,
} from "../../components/ui";
import { fmtDate, todayInput, weekStartInput } from "../../lib/format";
import ExportButtons from "../../components/ExportButtons";

interface Supplier {
  id: string;
  name: string;
  phone: string | null;
  status: "PENDING" | "ACTIVE";
}

const PAGE_SIZE = 50;

const emptySupplierForm = {
  name: "",
  phone: "",
  contact_person: "",
  address: "",
  city: "",
};

interface DropRow {
  drop: {
    id: string;
    drop_date: string;
    total_workers_dropped: number;
    rent_per_drop: number;
    status: "REGISTERED" | "COMPLETED";
  };
  supplier: { id: string; name: string; phone: string | null } | null;
}

export default function DropsPage() {
  const { facilityId: fid } = useFacilityScope();
  const { t } = useI18n();
  const [drops, setDrops] = useState<DropRow[] | null>(null);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [weekStart, setWeekStart] = useState(weekStartInput());
  const [showModal, setShowModal] = useState(false);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({
    supplier_id: "",
    drop_date: todayInput(),
    total_workers_dropped: 0,
    rent_per_drop: 0,
  });
  const [showAddSupplier, setShowAddSupplier] = useState(false);
  const [supplierBusy, setSupplierBusy] = useState(false);
  const [supplierForm, setSupplierForm] = useState(emptySupplierForm);
  const [supplierNotice, setSupplierNotice] = useState<{
    kind: "success" | "error";
    text: string;
  } | null>(null);

  const load = useCallback(() => {
    if (!fid) return;
    api<{ drops: DropRow[]; total: number }>(
      `/facility/${fid}/supplier-drops?weekStart=${weekStart}&page=${page}&pageSize=${PAGE_SIZE}&q=${encodeURIComponent(q)}&status=${status}`
    ).then((r) => {
      setDrops(r.drops);
      setTotal(r.total);
      if (page > Math.max(1, Math.ceil(r.total / PAGE_SIZE))) {
        setPage(Math.max(1, Math.ceil(r.total / PAGE_SIZE)));
      }
    });
  }, [fid, weekStart, page, q, status]);

  const loadSuppliers = useCallback(() => {
    if (!fid) return;
    api<{ suppliers: Supplier[] }>(`/facility/${fid}/suppliers`).then((r) =>
      setSuppliers(r.suppliers)
    );
  }, [fid]);

  useEffect(load, [load]);
  useEffect(loadSuppliers, [loadSuppliers]);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setBusy(true);
    try {
      await post(`/facility/${fid}/supplier-drops`, {
        supplier_id: form.supplier_id,
        drop_date: form.drop_date,
        total_workers_dropped: Number(form.total_workers_dropped),
        rent_per_drop: Number(form.rent_per_drop),
      });
      setShowModal(false);
      setForm({ ...form, supplier_id: "", total_workers_dropped: 0, rent_per_drop: 0 });
      load();
    } finally {
      setBusy(false);
    }
  }

  async function handleAddSupplier(e: FormEvent) {
    e.preventDefault();
    setSupplierBusy(true);
    setSupplierNotice(null);
    try {
      await post(`/facility/${fid}/suppliers`, {
        name: supplierForm.name,
        phone: supplierForm.phone || null,
        contact_person: supplierForm.contact_person || null,
        address: supplierForm.address || null,
        city: supplierForm.city || null,
      });
      setSupplierNotice({
        kind: "success",
        text: t("Supplier “{name}” added to this facility. Their login will be generated by the Super Admin.", { name: supplierForm.name }),
      });
      setShowAddSupplier(false);
      setSupplierForm(emptySupplierForm);
      loadSuppliers();
    } catch (err) {
      setSupplierNotice({
        kind: "error",
        text: err instanceof Error ? err.message : t("Failed to add supplier"),
      });
    } finally {
      setSupplierBusy(false);
    }
  }

  return (
    <div>
      <PageHeader
        title={t("Supplier Drops")}
        subtitle={t("Register daily supplier drops with negotiated rent per drop")}
        action={
          <div className="flex flex-wrap items-center gap-2">
            <ExportButtons reportType="drops" filters={{ from: weekStart }} />
            <Button variant="secondary" onClick={() => setShowAddSupplier(true)}>
              {t("+ Add supplier")}
            </Button>
            <Button onClick={() => setShowModal(true)}>{t("+ Register drop")}</Button>
          </div>
        }
      />

      {supplierNotice && (
        <div
          className={`animate-fade-in mb-4 whitespace-pre-line rounded-lg border px-4 py-3 text-sm ${
            supplierNotice.kind === "success"
              ? "border-onion-200 bg-onion-50 text-onion-800"
              : "border-red-200 bg-red-50 text-red-700"
          }`}
        >
          {supplierNotice.text}
        </div>
      )}

      <Card className="mb-5">
        <div className="flex items-center gap-3">
          <Field label={t("Week starting")}>
            <Input
              type="date"
              value={weekStart}
              onChange={(e) => {
                setWeekStart(e.target.value);
                setPage(1);
              }}
            />
          </Field>
        </div>
        <div className="mt-4">
          <ListFilters
            search={q}
            onSearch={(v) => {
              setQ(v);
              setPage(1);
            }}
            status={status}
            onStatus={(v) => {
              setStatus(v);
              setPage(1);
            }}
            statusOptions={[
              { value: "REGISTERED", label: t("Registered") },
              { value: "COMPLETED", label: t("Completed") },
            ]}
            searchPlaceholder={t("Search suppliers…")}
          />
        </div>
      </Card>

      {!drops ? (
        <LoadingScreen />
      ) : drops.length === 0 ? (
        <Card>
          {q || status ? (
            <EmptyState icon="🔍" title={t("No drops match")} hint={t("Try a different search or status filter")} />
          ) : (
            <EmptyState title={t("No drops this week")} hint={t("Register a supplier drop to begin")} />
          )}
        </Card>
      ) : (
        <Card>
          <Table head={[t("Supplier"), t("Date"), t("Workers"), t("Rent / drop"), t("Status")]} empty={null}>
            {drops.map((r) => (
              <tr key={r.drop.id} className="hover:bg-field-50/50">
                <Td className="font-semibold text-field-900">{r.supplier?.name ?? "—"}</Td>
                <Td>{fmtDate(r.drop.drop_date)}</Td>
                <Td>{r.drop.total_workers_dropped}</Td>
                <Td><Money value={r.drop.rent_per_drop} /></Td>
                <Td><StatusBadge status={r.drop.status} /></Td>
              </tr>
            ))}
          </Table>
          <Pagination
            page={page}
            totalPages={Math.max(1, Math.ceil(total / PAGE_SIZE))}
            total={total}
            pageSize={PAGE_SIZE}
            onChange={setPage}
          />
        </Card>
      )}

      <Modal open={showModal} onClose={() => setShowModal(false)} title={t("Register supplier drop")}>
        <form onSubmit={handleSubmit} className="space-y-4">
          <Field label={t("Supplier")}>
            <SearchableSelect
              value={form.supplier_id}
              onChange={(v) => setForm({ ...form, supplier_id: v })}
              options={suppliers.map((s) => ({
                value: s.id,
                label: s.status === "PENDING" ? `${s.name} (pending login)` : s.name,
              }))}
              placeholder={t("Select supplier…")}
              searchPlaceholder={t("Search suppliers…")}
              required
            />
            <p className="mt-1 text-[11px] text-field-400">
              {t("Need someone new? Use “+ Add supplier” — Super Admin activates their login.")}
            </p>
          </Field>
          <Field label={t("Drop date")}>
            <Input type="date" value={form.drop_date} onChange={(e) => setForm({ ...form, drop_date: e.target.value })} required />
          </Field>
          <div className="grid grid-cols-2 gap-3">
            <Field label={t("Workers dropped")}>
              <Input type="number" min={0} value={form.total_workers_dropped} onChange={(e) => setForm({ ...form, total_workers_dropped: Number(e.target.value) })} required />
            </Field>
            <Field label={t("Rent per drop (₹)")} hint={t("Negotiated amount")}>
              <Input type="number" min={0} value={form.rent_per_drop} onChange={(e) => setForm({ ...form, rent_per_drop: Number(e.target.value) })} required />
            </Field>
          </div>
          <div className="rounded-lg bg-onion-50 px-3 py-2 text-xs text-onion-800">
            {t("Rent is negotiated per drop — it may vary even for the same worker count.")}
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="secondary" onClick={() => setShowModal(false)}>{t("Cancel")}</Button>
            <Button type="submit" loading={busy}>{t("Register drop")}</Button>
          </div>
        </form>
      </Modal>

      <Modal
        open={showAddSupplier}
        onClose={() => setShowAddSupplier(false)}
        title="Add supplier"
      >
        <form onSubmit={handleAddSupplier} className="space-y-4">
          <div className="rounded-lg bg-onion-50 px-3 py-2 text-xs text-onion-800">
            {t("This supplier is registered for this facility only. They won't be selectable elsewhere until the Super Admin generates their login.")}
          </div>
          <Field label={t("Supplier name")}>
            <Input
              value={supplierForm.name}
              onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })}
              required
            />
          </Field>
          <div className="grid grid-cols-2 gap-3">
            <Field label={t("Phone")}>
              <Input
                value={supplierForm.phone}
                onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })}
              />
            </Field>
            <Field label={t("Contact person")}>
              <Input
                value={supplierForm.contact_person}
                onChange={(e) =>
                  setSupplierForm({ ...supplierForm, contact_person: e.target.value })
                }
              />
            </Field>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <Field label={t("Address")}>
              <Input
                value={supplierForm.address}
                onChange={(e) => setSupplierForm({ ...supplierForm, address: e.target.value })}
              />
            </Field>
            <Field label={t("City")}>
              <Input
                value={supplierForm.city}
                onChange={(e) => setSupplierForm({ ...supplierForm, city: e.target.value })}
              />
            </Field>
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="secondary" onClick={() => setShowAddSupplier(false)}>
              {t("Cancel")}
            </Button>
            <Button type="submit" loading={supplierBusy}>{t("Add supplier")}</Button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
